### ISSUE TITLE
`error: aborting due to 131 previous errors` when installing with cargo install

### ISSUE THREAD

**Issue by Reconcyl** [CensoredUsername/whitespace-rs#2]
I tried to build this program using `cargo install`:

    $ cargo install whitespacers

When I do this, I get 131 errors originating from the files `src/core/compiler_x64.rs` and `src/core/allocator.rs`. Most are of the form ``expected value, found module `self` `` or ``cannot find value `...` in this scope`` for some variable `...`.

My rustc/cargo version is `1.45.0`.

I also tried installing it with `cargo install +nightly whitespace-rs`, but this led to a separate set of compilation errors relating to `Span::mixed_site()` when compiling `dynasm`.

Is it recommended that I build from source instead of using `cargo install`?

**Edit**: I attempted to build from source and got the same errors (stable and nightly).

**Comment by CensoredUsername** [comment]
The minimum required rust version is 1.46.0 (either stable or nightly) as that version fixes some issues around macro_rules! and proc_macro hygiene interactions.

**Comment by Reconcyl** [comment]
Thanks, this solved the problem.
