### ISSUE TITLE
Incorrect compiler behavior?

### ISSUE THREAD

**Issue by Yu212** [CensoredUsername/whitespace-rs#4]
While using this compiler for [competitive programming](https://atcoder.jp/), I discovered two behaviors of this compiler that differ from [the official interpreter](https://web.archive.org/web/20150717140342/http://compsoc.dur.ac.uk/whitespace/download.php) and many other compilers.

This compiler interprets `\n` as 0, whereas other implementation interprets `__\n` or `\t_\n` as 0.

This compiler copies the nth value from the bottom of the stack with the Copy instruction. other implementation copies the nth value from the top of the stack.
If the Copy instruction is called in a function, it is not possible to know the offset of the stack at compile time, so it is more appropriate to use the index from the top of the stack.

Are these behaviors intended? If not, would you correct them? (I'm also interested in contributing a PR)

**Comment by CensoredUsername** [comment]
>This compiler interprets \n as 0, whereas other implementation interprets __ or \t_ as 0.

This compiler implements those as `0` as well. If my haskell is correct then there's 5 valid ways of writing 0 as an integer: The fully formed `__\n` and `\t_\n`, and the shorter technically incomplete `\n`, `_\n` and `\t\n`.

The spec is a bit vague on what the incomplete ones would be (as the first data bit and/or the sign bit) get lost, but the official interpreter does accept them as 0.

>This compiler copies the nth value from the bottom of the stack with the Copy instruction. other implementation copies the nth value from the top of the stack.

The official page is very unclear about what Copy does. Looking at the reference interpreter, you may be correct here.
It does seem that Copy is used very rarely then. I've never encountered a whitespace program that failed due to this mismatch.

That does seem more logical as well. Feel free to make a pull request.

edit: looking through the ecosystem I can find both ways implemented. Seems like this was the source of much confusion.

**Comment by Yu212** [comment]
Sorry about the first one, I had checked that the `__\n` was causing the error, but in fact it was because my editor adding a `\n` at the end of the code.
I'll PR about the second one later. Thank you!

**Comment by CensoredUsername** [comment]
I think I already have a fix in `f52bd3d`. Mind testing that instead?

**Comment by Yu212** [comment]
Wow thank you for implementing it.
How should I test? I confirmed that the code I had in mind works correctly (same as the official interpreter) with `mod.rs/interpret_block` and `compiler_x64.rs/compile`

```asm
    push 123
    call func
    pop
    push 10
loop:
    push 1
    push 2
    push 3
    copy 1
    pnum
    pop
    pop
    pop
    push 1
    sub
    dup
    jz end
    jmp loop
end:
    exit

func:
    push 456
    copy 1
    pnum
    pop
    ret
```

**Comment by CensoredUsername** [comment]
If it worked for you, that's fine. Just wanted to confirm I indeed implemented the right behaviour now. I'll close this and make a new release!

**Comment by Yu212** [comment]
Okay, thank you!

**Comment by thaliaarchi** [comment]
@Yu212 You mentioned that you're doing competitive programming on atcoder.jp with Whitespace? I maintain the [Whitespace Corpus](https://github.com/wspace/corpus) and one of the things I track is competitions which use Whitespace. However, when I look through the site and search with `site:atcoder.jp whitespace`, I see nothing relevant. Is Whitespace one of the supported languages you can write submissions in? Or do some challenges deal with the language somehow? I'm curious about what you can tell me about it.

**Comment by Yu212** [comment]
Yes, whitespace is one of the supported languages for all problems, you can see a list of [my submissions](https://kenkoooo.com/atcoder/#/user/Yu_212?userPageTab=Submissions) and [those of the Language Owner](https://kenkoooo.com/atcoder/#/user/ducktail?userPageTab=Submissions) (the person who solved the most problems using whitespace) from AtCoder Problems.

**Comment by thaliaarchi** [comment]
Thanks! Maybe I'll try to figure out how to scrape all the submissions in Whitespace, so I could aggregate them into a repo…

**Comment by Yu212** [comment]
AtCoder Problems has a [dataset of all the submissions](https://github.com/kenkoooo/AtCoderProblems/blob/master/doc/api.md), so maybe you can use this instead of scraping AtCoder.
